"""add_missing_indexes_for_query_performance

Revision ID: 1c10e82396fe
Revises: 4827f0ecff5d

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c10e82396fe"
down_revision: Union[str, Sequence[str], None] = "4827f0ecff5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_jobs_org_created_desc", "analysis_jobs", ["org_id", sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index("ix_users_org_id", "users", ["org_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_users_org_id", table_name="users")
    op.drop_index("ix_jobs_org_created_desc", table_name="analysis_jobs")
    # ### end Alembic commands ###
